spring:
  #mysql的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seek_food_fund
    username: root
    password: 439176

fund:
  self:
    params:
      rules:
        fund-id-start: 1
        fund-id-capacity: 10000000000000
    redis:
      key:
        name:
          fund-id-count: "fund:id:count"
        duration:
    jvm-caffeine: