spring:
  cloud:
    gateway:
      httpclient:
        forward-headers-strategy: native
      server:
        webflux:
          default-filters:
            # 给所有响应添加统一请求头标识
            - AddRequestHeader=origin,gateway
            - StripPrefix=1   #去除掉第一段路径
          routes:
            - id: user   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[0].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[0].id}/**    #路径断言，代表将路径为user的都转发

            - id: merchant   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[1].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[1].id}/**    #路径断言，代表将路径为user的都转发

            - id: employee   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[2].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[2].id}/**    #路径断言，代表将路径为user的都转发

            - id: meal   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[3].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[3].id}/**    #路径断言，代表将路径为user的都转发

            - id: fund   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[4].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[4].id}/**    #路径断言，代表将路径为user的都转发

            - id: promotion   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[5].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[5].id}/**    #路径断言，代表将路径为user的都转发

            - id: order   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[6].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[6].id}/**    #路径断言，代表将路径为user的都转发

            - id: rider   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[7].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[7].id}/**    #路径断言，代表将路径为user的都转发

            - id: comment   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[8].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[8].id}/**    #路径断言，代表将路径为user的都转发

            - id: interaction   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[9].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[9].id}/**    #路径断言，代表将路径为user的都转发

            - id: admin   #路由标识,必须唯一
              uri: lb://${spring.cloud.gateway.server.webflux.routes[10].id}   #路由地址，lb代表负载均衡，user代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/${spring.cloud.gateway.server.webflux.routes[10].id}/**    #路径断言，代表将路径为user的都转发

#            - id: Social   #路由标识,必须唯一
#              uri: lb://Social   #路由地址，lb代表负载均衡，Social代表模块服务名。该项可以直接用ip地址代替
#              predicates:       #断言，判断是否转发给该路由
#                - Path=/Social/**    #路径断言，代表将路径为Social的都转发